### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by dmytroyarmak** [dmytroyarmak/Backbone.dropboxDatastore#1]
- [x] write code for find
- [x] write code for findAll
- [x] write code for create
- [x] write code for destroy
- [x] write code for update
- [x] write some docs
- [x] use grunt instead of Makefile to minify
- [x] use grunt instead of Makefile to run test
- [x] use grunt to JSHint
- [x] use jasmine for testing engine
- [x] add jsHint config file
- [x] publish to Bower
- [x] publish to npm
- [x] add licence to package.json
